### PR TITLE
Fix save replay chats example in manual

### LINKED ISSUE #10: Invalid example in MANUAL.MD
This example won't do anything since the async iterator doesn't do iterations eagerly as arrays do and method like `.toArray()` may help to do all the iterations.

```js 
 import { Masterchat } from "masterchat"; 
 import { appendFile, writeFile, readFile } from "node:fs/promises"; 
  
 const mc = await Masterchat.init("<videoId>"); 
  
 await mc 
   .iter() 
   .filter((action) => action.type === "addChatItemAction") // only chat events 
   .map((chat) => JSON.stringify(chat) + "\n") // convert to JSONL 
   .map((jsonl) => appendFile("./chats.jsonl", jsonl)); // append to the file 
```

### PR DESCRIPTION
**Pull request by MadProbe**
This PR fixes incorrect example in Manual.md.
Fixes #10

### CODE REVIEW

**Comment by MadProbe** [comment]
Sorry, but only now i realized that the .forEach method could be used instead of .map + .toArray

**Comment by uetchy** [comment]
Yeah but filter and map is cooler

**Comment by uetchy** [comment]
Make sure to mark the PR ready for review when finished

**Comment by MadProbe** [comment]
Done :)

**Review by uetchy — APPROVED** [review]

**Comment by uetchy** [comment]
@all-contributors add @MadProbe for docs

**Pull request merged**
